fix s3 sorting by file size bug
one2nc/cloudlens pull request #23
Opened 2023-09-26 08:08 UTC by PratikJethe

2023-09-27 06:24 UTC, jdk2588 requested changes
Please link the PR with the issue.

2023-09-27 06:24 UTC, jdk2588 commented on internal/ui/table.go
> +	if !h.Hide{
Write the hide condition like this
```
		if h[c].Hide {
			col++
			continue
		}
```

2023-09-27 11:20 UTC, PratikJethe commented on internal/ui/table.go
> +	if !h.Hide{
done

2023-09-29 06:09 UTC, jdk2588 approved these changes

2023-09-29 06:09 UTC, merged